name: PhaniTeja
email: thedecipher.sp@gmail.com
github_username: sphanit

markdown: kramdown
permalink: /blog/:title

theme: jekyll-theme-tactile
disqus:
  shortname: https-sphanit-github-io-blog-test
# other options
